# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('accessibility', models.BooleanField()),
                ('money', models.BooleanField()),
                ('parentalconsent', models.TextField()),
                ('age', models.TextField()),
                ('transportation', models.TextField()),
                ('openingTime', models.BooleanField()),
                ('closingTime', models.BooleanField()),
                ('contact', models.TextField()),
                ('insurance', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
