# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('chat', models.BooleanField(default=False)),
                ('hotline', models.TextField(default='')),
                ('self_health', models.BooleanField(default=False)),
                ('therapy', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=False)),
                ('audio', models.BooleanField(default=False)),
                ('affirmations', models.BooleanField(default=False)),
                ('animals', models.BooleanField(default=False)),
                ('c_visuals', models.BooleanField(default=False)),
                ('hobbies', models.BooleanField(default=False)),
                ('meditate', models.BooleanField(default=False)),
                ('spaces', models.BooleanField(default=False)),
                ('vent', models.BooleanField(default=False)),
                ('visuals', models.BooleanField(default=False)),
            ],
        ),
    ]
