# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='hotline',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='self_health',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='sounds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='therapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='accessibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='age',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='closingTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='issue',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='money',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='openingTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='parentalconsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='transportation',
            field=models.TextField(default=''),
        ),
    ]
