# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170818_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='sounds',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='accessibility',
            new_name='wheelchair_accessible',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='age',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='closingTime',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='openingTime',
        ),
        migrations.AddField(
            model_name='resource',
            name='affirmations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='c_visuals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='hobbies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_age',
            field=models.TextField(default='99'),
        ),
        migrations.AddField(
            model_name='resource',
            name='meditate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_age',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='resource',
            name='spaces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='vent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='visuals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contact',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='resource',
            name='transportation',
            field=models.BooleanField(default=False),
        ),
    ]
