# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170818_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='issue',
        ),
    ]
