# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170821_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='hotline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='self_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='therapy',
            field=models.BooleanField(default=False),
        ),
    ]
