# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170821_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='hotline',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='money',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='parentalconsent',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='self_health',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='therapy',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='wheelchair_accessible',
        ),
    ]
