# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170821_1205'),
        ('blog', '0005_auto_20170821_1204'),
    ]

    operations = [
    ]
